---
title: "Using scheduler with dataframes"
author: "James Laird-Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(tidyverse)
library(anomalize)
library(lubridate)
```

```{r}
#tidyverse_cran_downloads <- data(tidyverse_cran_downloads, package = "anomalize")
```

```{r}
tidyverse_cran_downloads
```

```{r}
on_christmas  <- on_mday(25) %>% only_occuring(in_month("Dec"))

on_weeked <- on_wday("Sat") %>% also_occuring(on_wday("Sun"))
```

```{r}
View(on_christmas)
```

```{r}
View(on_christmas[1])
```


```{r}
test_date(dmy("25/12/1990"), on_christmas)
```

```{r}
on_christmas  <- on_mday(25) %>% only_occuring(in_month("Dec"))

if(is_date_element(on_christmas[[1]])){
  on_christmas[[1]] <- date_eval(on_christmas[[1]], dmy("24/12/1990"))
}

can_recon(on_christmas)
```

```{r}
bench::mark(rlang::is_false(on_christmas[[1]]),
            on_christmas[[1]] == FALSE
            #identical(on_christmas[[1]], FALSE)
            )
```

```{r}
on_christmas[[1]]
```


```{r}
tidyverse_cran_downloads %>% 
  mutate(day_type = case_when(
    test_date(date, on_christmas) ~ "Christmas",
    test_date(date, on_weeked) ~ "Weekend",
    TRUE ~ "Normal Day"
  ))
```

```{r}
schedule(x = on_christmas, from = dmy("01/01/1990"), to = dmy("01/01/2010"))
```

